### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by hme0354** [TA2k/ioBroker.zehnder-cloud#1]
Every time I try to install it, I'm getting this error:

`$ iobroker url https://github.com/TA2k/ioBroker.zehnder-cloud --host raspberrypi

install TA2k/ioBroker.zehnder-cloud#6067b08261a7ea03a438701466010d13e2327e00

NPM version: 6.14.9

npm install TA2k/ioBroker.zehnder-cloud#6067b08261a7ea03a438701466010d13e2327e00 --loglevel error --prefix "/opt/iobroker" (System call)`

**Comment by TA2k** [comment]
I dont see an error please follow this manual:
https://forum.iobroker.net/topic/47856/test-adapter-zehnder-cloud-v-0-0-1
