### ISSUE TITLE
Error extract keys / TypeError

### ISSUE THREAD

**Issue by pp80-git** [TA2k/ioBroker.zehnder-cloud#3]
After installing and starting the adapter I get the following error messages:
Error extract keys: 9128 ...
TypeError: Cannot read property 'write' of undefined

Attached the log file

[ioBroker.log](https://github.com/TA2k/ioBroker.zehnder-cloud/files/7584585/ioBroker.log)

**Comment by TA2k** [comment]
Please reinstall again from github error should be solved

**Comment by pp80-git** [comment]
Thank you, the problem is solved.
But the decimal separator seems to be missing for temperatures.

**Comment by TA2k** [comment]
Is this maybe possible to change this on the vis?
