### ISSUE TITLE
Temperatur Values are more like RAW Values as they need to be devided by 10

### ISSUE THREAD

**Issue by felsnerino** [TA2k/ioBroker.zehnder-cloud#5]
**Describe the bug**  
Temperature values are shown without seperator. For example "exhaustAirTemp" is shown 226 for 22,6°C. So you have to always process the values after they have been saved/or replicate all items, so that they can be stored as °C.

**To Reproduce**  
Is allways active.

**Expected behavior**  
All Temp(erature) Values should be converted to °C so that they can be used straight away either in IOBroker or wherever.

**Screenshots & Logfiles**  
Just look at the objects section.

**Versions:**  
 - Adapter version: 0.0.6

**Additional context**  
n/a

**Comment by felsnerino** [comment]
Thanks a lot for the adapter anyway. It is great, as now, I can also read the Ground Heat Exchange values, that was not possible with other adapters!!

**Comment by TA2k** [comment]
I adjusted this in the GitHub version. Reinstall via GitHub. delete alle states. restart instance

**Comment by TA2k** [comment]
Please try again the same steps

**Comment by felsnerino** [comment]
ok, great now it works. I can see the new values. Would it also make sense to apply this to the temperature values of the properties? Like coolProfileTemp etc. I think then only 2 more would be left, that are temperature, but not falling into the same namingconvetion you used in the new code ("endswith temp"): limitRMOTCooling and limitRMOTHeating. Thanks a lot in any case for the change!!!

**Comment by TA2k** [comment]
I added limitRMOT
